junit_tests(
  name='lexer_test',
  sources=['LexerTest.java'],
  dependencies=[
    'src/antlr/org/oxlang/lang:parser',
    '3rdparty/jvm:antlr4',
  ]
)

junit_tests(
  name='reader_test',
  sources=['ReaderTest.java'],
  dependencies=[
    'src/java/org/oxlang/lang:reader',
  ],
)
